function [time,current,noisyCurrent] = simulateData(sequence,timing,fs)

% Stephen Fleming
% June 17, 2014

% Takes an input sequence of bases (e.g. ATCATTGCAACGT...) and an integer k
% and the variable "timing," which is either 0 (for an exponential
% distribution of level durations) or a number for the duration of levels
% in milliseconds, and returns a current signal as if from data sampled at
% frequency fs.  The current signal returned is actually a fraction of the
% open pore current, and so is unitless.

%% Using the Oxford lambda DNA sequence
% The sequence of the 3.6kb piece of lambda DNA from Oxford, ONLA11063 with
% AE317 leader is (I have guessed nitroindole is like a G...):

% sequence = 'XXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTXXXXGGTTGTTTCTGTTGGTGCTGATATTGCCCCCGCCATCAGATTGTGTTTGTTAGTCGCTGCCATCAGATTGTGTTTGTTAGTCGCTTTTTTTTTTTGGAATTTTTTTTTTGGAATTTTTTTTTTGCGCTAACAACCTCCTGCCGTTTTGCCCGTGCATATCGGTCACGAACAAATCTGATTACTAAACACAGTAGCCTGGATTTGTTCTATCAGTAATCGACCTTATTCCTAATTAAATAGAGCAAATCCCCTTATTGGGGGTAAGACATGAAGATGCCAGAAAAACATGACCTGTTGGCCGCCATTCTCGCGGCAAAGGAACAAGGCATCGGGGCAATCCTTGCGTTTGCAATGGCGTACCTTCGCGGCAGATATAATGGCGGTGCGTTTACAAAAACAGTAATCGACGCAACGATGTGCGCCATTATCGCCTAGTTCATTCGTGACCTTCTCGACTTCGCCGGACTAAGTAGCAATCTCGCTTATATAACGAGCGTGTTTATCGGCTACATCGGTACTGACTCGATTGGTTCGCTTATCAAACGCTTCGCTGCTAAAAAAGCCGGAGTAGAAGATGGTAGAAATCAATAATCAACGTAAGGCGTTCCTCGATATGCTGGCGTGGTCGGAGGGAACTGATAACGGACGTCAGAAAACCAGAAATCATGGTTATGACGTCATTGTAGGCGGAGAGCTATTTACTGATTACTCCGATCACCCTCGCAAACTTGTCACGCTAAACCCAAAACTCAAATCAACAGGCGCCGGACGCTACCAGCTTCTTTCCCGTTGGTGGGATGCCTACCGCAAGCAGCTTGGCCTGAAAGACTTCTCTCCGAAAAGTCAGGACGCTGTGGCATTGCAGCAGATTAAGGAGCGTGGCGCTTTACCTATGATTGATCGTGGTGATATCCGTCAGGCAATCGACCGTTGCAGCAATATCTGGGCTTCACTGCCGGGCGCTGGTTATGGTCAGTTCGAGCATAAGGCTGACAGCCTGATTGCAAAATTCAAAGAAGCGGGCGGAACGGTCAGAGAGATTGATGTATGAGCAGAGTCACCGCGATTATCTCCGCTCTGGTTATCTGCATCATCGTCTGCCTGTCATGGGCTGTTAATCATTACCGTGATAACGCCATTACCTACAAAGCCCAGCGCGACAAAAATGCCAGAGAACTGAAGCTGGCGAACGCGGCAATTACTGACATGCAGATGCGTCAGCGTGATGTTGCTGCGCTCGATGCAAAATACACGAAGGAGTTAGCTGATGCTAAAGCTGAAAATGATGCTCTGCGTGATGATGTTGCCGCTGGTCGTCGTCGGTTGCACATCAAAGCAGTCTGTCAGTCAGTGCGTGAAGCCACCACCGCCTCCGGCGTGGATAATGCAGCCTCCCCCCGACTGGCAGACACCGCTGAACGGGATTATTTCACCCTCAGAGAGAGGCTGATCACTATGCAAAAACAACTGGAAGGAACCCAGAAGTATATTAATGAGCAGTGCAGATAGAGTTGCCCATATCGATGGGCAACTCATGCAATTATTGTGAGCAATACACACGCGCTTCCAGCGGAGTATAAATGCCTAAAGTAATAAAACCGAGCAATCCATTTACGAATGTTTGCTGGGTTTCTGTTTTAACAACATTTTCTGCGCCGCCACAAATTTTGGCTGCATCGACAGTTTTCTTCTGCCCAATTCCAGAAACGAAGAAATGATGGGTGATGGTTTCCTTTGGTGCTACTGCTGCCGGTTTGTTTTGAACAGTAAACGTCTGTTGAGCACATCCTGTAATAAGCAGGGCCAGCGCAGTAGCGAGTAGCATTTTTTTCATGGTGTTATTCCCGATGCTTTTTGAAGTTCGCAGAATCGTATGTGTAGAAAATTAAACAAACCCTAAACAATGAGTTGAAATTTCATATTGTTAATATTTATTAATGTATGTCAGGTGCGATGAATCGTCATTGTATTCCCGGATTAACTATGTCCACAGCCCTGACGGGGAACTTCTCTGCGGGAGTGTCCGGGAATAATTAAAACGATGCACACAGGGTTTAGCGCGTACACGTATTGCATTATGCCAACGCCCCGGTGCTGACACGGAAGAAACCGGACGTTATGATTTAGCGTGGAAAGATTTGTGTAGTGTTCTGAATGCTCTCAGTAAATAGTAATGAATTATCAAAGGTATAGTAATATCTTTTATGTTCATGGATATTTGTAACCCATCGGAAAACTCCTGCTTTAGCAAGATTTTCCCTGTATTGCTGAAATGTGATTTCTCTTGATTTCAACCTATCATAGGACGTTTCTATAAGATGCGTGTTTCTTGAGAATTTAACATTTACAACCTTTTTAAGTCCTTTTATTAACACGGTGTTATCGTTTTCTAACACGATGTGAATATTATCTGTGGCTAGATAGTAAATATAATGTGAGACGTTGTGACGTTTTAGTTCAGAATAAAACAATTCACAGTCTAAATCTTTTCGCACTTGATCGAATATTTCTTTAAAAATGGCAACCTGAGCCATTGGTAAAACCTTCCATGTGATACGAGGGCGCGTAGTTTGCATTATCGTTTTTATCGTTTCAATCTGGTCTGACCTCCTTGTGTTTTGTTGATGATTTATGTCAAATATTAGGAATGTTTTCACTTAATAGTATTGGTTGCGTAACAAAGTGCGGTCCTGCTGGCATTCTGGAGGGAAATACAACCGACAGATGTATGTAAGGCCAACGTGCTCAAATCTTCATACAGAAAGATTTGAAGTAATATTTTAACCGCTAGATGAAGAGCAAGCGCATGGAGCGACAAAATGAATAAAGAACAATCTGCTGATGATCCCTCCGTGGATCTGATTCGTGTAAAAAATATGCTTAATAGCACCATTTCTATGAGTTACCCTGATGTTGTAATTGCATGTATAGAACATAAGGTGTCTCTGGAAGCATTCAGAGCAATTGAGGCAGCGTTGGTGAAGCACGATAATAATATGAAGGATTATTCCCTGGTGGTTGACTGATCACCATAACTGCTAATCATTCAAACTATTTAGTCTGTGACAGAGCCAACACGCAGTCTGTCACTGTCAGGAAAGTGGTAAAACTGCAACTCAATTACTGCAATGCCCTCGTAATTAAGTGAATTTACAATATCGTCCTGTTCGGAGGGAAGAACGCGGGATGTTCATTCTTCATCACTTTTAATTGATGTATATGCTCTCTTTTCTGACGTTAGTCTCCGACGGCAGGCTTCAATGACCCAGGCTGAGAAATTCCCGGACCCTTTTTGCTCAAGAGCGATGTTAATTTGTTCAATCATTTGGTTAGGAAAGCGGATGTTGCGGGTTGTTGTTCTGCGGGTTCTGTTCTTCGTTGACATGAGGTTGCCCCGTATTCAGTGTCGCTGATTTGTATTGTCTGAAGTTGTTTTTACGTTAAGTTGATGCAGATCAATTAATACGATACCTGCGTCATAATTGATTATTTGACGTGGTTTGATGGCCTCCACGCACGTTGTGATATGTAGATGATAATCATTATCACTTTACGGGTCCTTTCCGGTGAAAAAAAAGGTACCAAAAAAAACATCGTCGTGAGTAGTGAACCGTAAGCTGCGTTCTGTTTCGGATGTATGTTTTCATACATCCGAAACAGAACGCAGCTTACGGTTCACTACTCACGACGATGTTTTTTTTGGTACCTTTTTTTTCACCGGAAAGGACCCGTAAAGTGATAATGATTATCATCTACATATCACAACGTGCGTGGAGGCCATCAAACCACGTCAAATAATCAATTATGACGCAGGTATCGTATTAATTGATCTGCATCAACTTAACGTAAAAACAACTTCAGACAATACAAATCAGCGACACTGAATACGGGGCAACCTCATGTCAACGAAGAACAGAACCCGCAGAACAACAACCCGCAACATCCGCTTTCCTAACCAAATGATTGAACAAATTAACATCGCTCTTGAGCAAAAAGGGTCCGGGAATTTCTCAGCCTGGGTCATTGAAGCCTGCCGTCGGAGACTAACGTCAGAAAAGAGAGCATATACATCAATTAAAAGTGATGAAGAATGAACATCCCGCGTTCTTCCCTCCGAACAGGACGATATTGTAAATTCACTTAATTACGAGGGCATTGCAGTAATTGAGTTGCAGTTTTACCACTTTCCTGACAGTGACAGACTGCGTGTTGGCTCTGTCACAGACTAAATAGTTTGAATGATTAGCAGTTATGGTGATCAGTCAACCACCAGGGAATAATCCTTCATATTATTATCGTGCTTCACCAACGCTGCCTCAATTGCTCTGAATGCTTCCAGAGACACCTTATGTTCTATACATGCAATTACAACATCAGGGTAACTCATAGAAATGGTGCTATTAAGCATATTTTTTACACGAATCAGATCCACGGAGGGATCATCAGCAGATTGTTCTTTATTCATTTTGTCGCTCCATGCGCTTGCTCTTCATCTAGCGGTTAAAATATTACTTCAAATCTTTCTGTATGAAGATTTGAGCACGTTGGCCTTACATACATCTGTCGGTTGTATTTCCCTCCAGAATGCCAGCAGGACCGCACTTTGTTACGCAACCAATACTATTAAGTGAAAACATTCCTAATATTTGACATAAATCATCAACAAAACACAAGGAGGTCAGACCAGATTGAAACGATAAAAACGATAATGCAAACTACGCGCCCTCGTATCACATGGAAGGTTTTACCAATGGCTCAGGTTGCCATTTTTAAAGAAATATTCGATCAAGTGCGAAAAGATTTAGACTGTGAATTGTTTTATTCTGAACTAAAACGTCACAACGTCTCACATTATATTTACTATCTAGCCACAGATAATATTCACATCGTGTTAGAAAACGATAACACCGTGTTAATAAAAGGACTTAAAAAGGTTGTAAATGTTAAATTCTCAAGAAACACGCATCTTATAGAAACGTCCTATGATAGGTTGAAATCAAGAGAAATCACATTTCAGCAATACAGGGAAAATCTTGCTAAAGCAGGAGTTTTCCGATGGGTTACAAATATCCATGAACATAAAAGATATTACTATACCTTTGATAATTCATTACTATTTACTGAGAGCATTCAGAACACTACACAAATCTTTCCACGCTAAATCATAACGTCCGGTTTCTTCCGTGTCAGCACCGGGGCGTTGGCATAATGCAATACGTGTACGCGCTAAACCCTGTGTGCATCGTTTTAATTATTCCCGGACACTCCCGCAGAGAAGTTCCCCGTCAGGGCTGTGGACATAGTTAATCCGGGAATACAATGACGATTCATCGCACCTGACATACATTAATAAATATTAACAATATGAAATTTCAACTCATTGTTTAGGGTTTGTTTAATTTTCTACACATACGATTCTGCGAACTTCAAAAAGCATCGGGAATAACACCATGAAAAAAATGCTACTCGCTACTGCGCTGGCCCTGCTTATTACAGGATGTGCTCAACAGACGTTTACTGTTCAAAACAAACCGGCAGCAGTAGCACCAAAGGAAACCATCACCCATCATTTCTTCGTTTCTGGAATTGGGCAGAAGAAAACTGTCGATGCAGCCAAAATTTGTGGCGGCGCAGAAAATGTTGTTAAAACAGAAACCCAGCAAACATTCGTAAATGGATTGCTCGGTTTTATTACTTTAGGCATTTATACTCCGCTGGAAGCGCGTGTGTATTGCTCACAATAATTGCATGAGTTGCCCATCGATATGGGCAACTCTATCTGCACTGCTCATTAATATACTTCTGGGTTCCTTCCAGTTGTTTTTGCATAGTGATCAGCCTCTCTCTGAGGGTGAAATAATCCCGTTCAGCGGTGTCTGCCAGTCGGGGGGAGGCTGCATTATCCACGCCGGAGGCGGTGGTGGCTTCACGCACTGACTGACAGACTGCTTTGATGTGCAACCGACGACGACCAGCGGCAACATCATCACGCAGAGCATCATTTTCAGCTTTAGCATCAGCTAACTCCTTCGTGTATTTTGCATCGAGCGCAGCAACATCACGCTGACGCATCTGCATGTCAGTAATTGCCGCGTTCGCCAGCTTCAGTTCTCTGGCATTTTTGTCGCGCTGGGCTTTGTAGGTAATGGCGTTATCACGGTAATGATTAACAGCCCATGACAGGCAGACGATGATGCAGATAACCAGAGCGGAGATAATCGCGGTGACTCTGCTCATACATCAATCTCTCTGACCGTTCCGCCCGCTTCTTTGAATTTTGCAATCAGGCTGTCAGCCTTATGCTCGAACTGACCATAACCAGCGCCCGGCAGTGAAGCCCAGATATTGCTGCAACGGTCGATTGCCTGACGGATATCACCACGATCAATCATAGGTAAAGCGCCACGCTCCTTAATCTGCTGCAATGCCACAGCGTCCTGACTTTTCGGAGAGAAGTCTTTCAGGCCAAGCTGCTTGCGGTAGGCATCCCACCAACGGGAAAGAAGCTGGTAGCGTCCGGCGCCTGTTGATTTGAGTTTTGGGTTTAGCGTGACAAGTTTGCGAGGGTGATCGGAGTAATCAGTAAATAGCTCTCCGCCTACAATGACGTCATAACCATGATTTCTGGTTTTCTGACGTCCGTTATCAGTTCCCTCCGACCACGCCAGCATATCGAGGAACGCCTTACGTTGATTATTGATTTCTACCATCTTCTACTCCGGCTTTTTTAGCAGCGAAGCGTTTGATAAGCGAACCAATCGAGTCAGTACCGATGTAGCCGATAAACACGCTCGTTATATAAGCGAGATTGCTACTTAGTCCGGCGAAGTCGAGAAGGTCACGAATGAACTAGGCGATAATGGCGCACATCGTTGCGTCGATTACTGTTTTTGTAAACGCACCGCCATTATATCTGCCGCGAAGGTACGCCATTGCAAACGCAAGGATTGCCCCGATGCCTTGTTCCTTTGCCGCGAGAATGGCGGCCAACAGGTCATGTTTTTCTGGCATCTTCATGTCTTACCCCCAATAAGGGGATTTGCTCTATTTAATTAGGAATAAGGTCGATTACTGATAGAACAAATCCAGGCTACTGTGTTTAGTAATCAGATTTGTTCGTGACCGATATGCACGGGCAAAACGGCAGGAGGTTGTTAGCGCAAAAAAAAAATTCCAAAAAAAAAATTCCAAAAAAAAAAAGCGACTAACAAACACAATCTGATGGCAGCGACTA';

%% Define current levels for homopolymer

% Taken from Table S1 in Derrington et al. 10.1073/pnas.1001831107
% from data taken at 180mV.  Given here as a fraction of open-pore current.

% A = 0.2;
% G = 0.18;
% C = 0.15;
% T = 0.13;
% X = 0.66; % abasic level based on Oxford data
% 
% %% Determine levels by averaging over k-mer
% 
% pureLevels = zeros(1,numel(sequence));
% 
% % First make a vector of just the levels for k=1
% for i = 1:numel(sequence)
%     switch sequence(i)
%         case 'A'
%             pureLevels(i) = A;
%         case 'G'
%             pureLevels(i) = G;
%         case 'C'
%             pureLevels(i) = C;
%         case 'T'
%             pureLevels(i) = T;
%         case 'X'
%             pureLevels(i) = X;
%         otherwise
%             display(['The base at position ' num2str(i) ' is invalid.']);
%             display('Valid bases are A, T, C, G, or X (for abasic).  Use no commas or spaces.')
%             current = [];
%     end
% end
% 
% % Now average levels over k-mer
% 
% averageLevels = zeros(1,numel(sequence)-2*floor(k/2)); % some bases at beginning and end won't be seen
% 
% for i = 1:numel(averageLevels)
%     averageLevels(i) = mean(pureLevels(i:i+k-1));
% end

%% Call function that uses Oxford's model

averageLevels = oxford_simulator(sequence,1)';

%% Determine timing of levels

if timing == 0
    % Pick from an exponential distribution with mean of 100ms
    t = cumsum(exprnd(0.1,1,numel(averageLevels)));
else
    % Levels have equal durations
    t = timing/1000:timing/1000:timing*(numel(averageLevels))/1000;
end

%% Populate 'current' with data from average levels and timing

current = zeros(1,floor(t(end)*fs));
a = 1;
for i = 1:numel(averageLevels)
    n = floor(t(i)*fs)-a;
    current(a:a+n) = averageLevels(i);
    a = a+n; % index
end

% Add noise (Gaussian with standard deviation of 1.6pA)
noisyCurrent = current + 1.6*randn(1,numel(current));

time = 0:(1/fs):t(end);
time = time(1:numel(current));

%% Plot it

figure(1)
clf
axes('FontSize',20)
plot(time,noisyCurrent)
hold on
plot(time,current,'r')
xlabel('Time (s)')
ylabel('Current (pA)')
%title('Simulated data from 3.6kb DNA: ONLA11063 with AE217 leader')
title('Simulated data')
annotation('textbox',[0.75 0.85 0 0],'String','k=5','FontSize',18)
axis tight
ylim([0 180])

end
